---
- name: Ensure Oh My Zsh dependencies are installed.
  become: "{{ ansible_distribution != 'MacOSX' }}"
  package:
    update_cache: true
    name: "{{ ohmyzsh_packages }}"
    state: present
    install_recommends: false
  
- name: Set zsh as a default shell.
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
    state: present
    
- name: Ensure Oh My Zsh repository is cloned.
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh
    dest: "{{ ohmyzsh_path }}"
    version: master

- name: Ensure {{ ohmyzsh_config_path }} is present.
  ansible.builtin.file:
    path: "{{ ohmyzsh_config_path }}"
    state: directory

- name: Install zsh initalization script.
  ansible.builtin.template:
    src: zshrc.j2
    dest: "{{ ohmyzsh_config_path }}/.zshrc"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644
